import { Head, useForm } from '@inertiajs/react';
import { KeyRound, Search } from 'lucide-react';
import { FormEvent } from 'react';

type Sale = { public_id: string; status: string; estimate_kg: number | null; created_at: string };
const canonical = ['submitted', 'under_review', 'accepted', 'pickup_scheduled', 'picked_up', 'closed'];
const statusLabel: Record<string, string> = { submitted: 'Terkirim', under_review: 'Sedang ditinjau', accepted: 'Diterima', rejected: 'Ditolak', pickup_scheduled: 'Pickup dijadwalkan', picked_up: 'Sudah dijemput', closed: 'Selesai' };
const statusText: Record<string, string> = { 'Pending review': 'Laporan sedang ditinjau petugas sebelum pickup dapat dijadwalkan.', pending_review: 'Laporan sedang ditinjau petugas sebelum pickup dapat dijadwalkan.', approved: 'Laporan disetujui dan menunggu pengaturan pickup.', scheduled: 'Pickup sudah dijadwalkan.', picked_up: 'Material sudah dijemput.', completed: 'Laporan selesai diproses.', rejected: 'Laporan belum dapat diproses.' };
export default function Tracking({ sale }: { sale?: Sale }) {
    const form = useForm({ public_id: '', pin: '' });
    const submit = (event: FormEvent) => { event.preventDefault(); form.post(route('tracking.show')); };
    return <><Head title="Lacak pickup — SayCle" /><main className="grid min-h-screen place-items-center bg-[#f4f3ed] px-5 text-[#18352a]"><section className="w-full max-w-md"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#e88c12]">SayCle · Tracking aman</p><h1 className="mt-3 text-5xl font-semibold tracking-[-.05em]">Lacak laporanmu.</h1>{sale ? <div className="mt-9 rounded-[2rem] bg-white p-7 shadow-xl shadow-[#18352a]/10"><p className="text-sm text-[#18352a]/60">Status laporan</p><strong className="mt-2 block text-3xl">{sale.status}</strong><p>{statusText[sale.status] ?? 'Status laporan sedang diperbarui.'}</p><dl className="mt-7 grid gap-3 border-t border-[#18352a]/10 pt-5 text-sm"><div className="flex justify-between"><dt>Sale ID</dt><dd className="max-w-[55%] break-all font-semibold">{sale.public_id}</dd></div><div className="flex justify-between"><dt>Perkiraan berat</dt><dd className="font-semibold">{sale.estimate_kg ?? '—'} kg</dd></div></dl></div> : <><p className="mt-5 leading-7 text-[#18352a]/65">Masukkan Sale ID dan PIN. ID saja tidak cukup untuk membuka status.</p><form onSubmit={submit} className="mt-9 space-y-4 rounded-[2rem] bg-white p-7 shadow-xl shadow-[#18352a]/10"><label className="block text-sm font-semibold">Sale ID<input required className="mt-2 min-h-12 w-full rounded-xl border border-[#18352a]/15 bg-[#f4f3ed] px-4" value={form.data.public_id} onChange={e => form.setData('public_id', e.target.value)} /></label><label className="block text-sm font-semibold"><KeyRound size={16} className="mr-2 inline" />PIN<input required inputMode="numeric" className="mt-2 min-h-12 w-full rounded-xl border border-[#18352a]/15 bg-[#f4f3ed] px-4 tracking-[.2em]" value={form.data.pin} onChange={e => form.setData('pin', e.target.value)} /></label><button disabled={form.processing} className="flex min-h-12 w-full items-center justify-center rounded-full bg-[#e88c12] font-bold">{form.processing ? 'Memeriksa…' : <><Search size={18} className="mr-2" />Lihat status</>}</button></form></>}</section></main></>;
}
