import AppLayout from '@/layouts/app-layout';
import { type BreadcrumbItem } from '@/types';
import { Head, Link } from '@inertiajs/react';

type Trip = { id: number; delivery_id: number; stop_order: number | null; load_kg: number; capacity_kg: number; officer: { name: string } | null; status: string; estimation_source: string | null; partner: { name: string | null; address: string | null } | null; metrics: { distance_m: number; duration_s: number } };
type Route = { vehicle_id: number; vehicle_name: string; capacity_kg: number; load_kg: number; trips: Trip[] };
type Unassigned = { delivery_id: number; partner: string | null; kg: number; reason: string };
export default function DeliveryRoutes({ selectedDate, deliveryRoutes = [], unassignedDeliveries = [] }: { selectedDate: string; deliveryRoutes?: Route[]; unassignedDeliveries?: Unassigned[] }) { return <AppLayout breadcrumbs={[{ title: 'Dasbor', href: '/dashboard' }, { title: 'Rute pengiriman', href: '/delivery-routes' }]}><Head title="Rute pengiriman" /><main className="min-h-full space-y-6 bg-[#f4f3ed] p-4 text-[#18352a] md:p-6"><header><h1 className="text-2xl font-semibold">Rute pengiriman</h1><p className="mt-1 text-sm text-[#18352a]/70">Rute tujuan mitra untuk {selectedDate}.</p></header>{deliveryRoutes.length === 0 && unassignedDeliveries.length === 0 ? <Empty /> : <><div className="grid gap-4 lg:grid-cols-2">{deliveryRoutes.map((route) => <section key={route.vehicle_id} className="rounded-2xl border border-[#2f6848]/15 bg-white p-5"><div className="flex justify-between"><h2 className="font-semibold">{route.vehicle_name}</h2><span className="text-sm tabular-nums">{route.load_kg} / {route.capacity_kg} kg</span></div><ol className="mt-4 space-y-3 border-t pt-3">{route.trips.map((trip) => <li key={trip.id} className="flex gap-3 text-sm"><b>{trip.stop_order ?? '—'}.</b><div><Link href={`/delivery-routes/${route.vehicle_id}?service_date=${selectedDate}`} className="font-semibold hover:underline">{trip.partner?.name ?? 'Mitra tidak tersedia'}</Link><p className="text-[#18352a]/65">{trip.partner?.address ?? 'Alamat tidak tersedia'} · {trip.load_kg} kg · {trip.officer?.name ?? 'Officer belum ditugaskan'}</p><p className="text-xs text-[#18352a]/55">{trip.estimation_source ?? 'Sumber estimasi tidak tersedia'} · {trip.metrics.distance_m} m · {Math.round(trip.metrics.duration_s / 60)} mnt</p></div></li>)}</ol></section>)}</div>{unassignedDeliveries.length > 0 && <section className="rounded-2xl border border-[#e88c12]/40 bg-white p-5"><h2 className="font-semibold">Menunggu penugasan</h2><ul className="mt-3 space-y-2 text-sm">{unassignedDeliveries.map((item) => <li key={item.delivery_id} className="flex justify-between gap-3"><span>{item.partner ?? 'Mitra tidak tersedia'} · {item.kg} kg</span><span className="text-[#18352a]/65">{item.reason}</span></li>)}</ul></section>}</>}</main></AppLayout>; }
function Empty() { return <section className="rounded-2xl border border-dashed border-[#2f6848]/25 bg-white py-16 text-center text-sm text-[#18352a]/70">Belum ada rute pengiriman untuk tanggal ini.</section>; }
